/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

import DAO.DAOactividadImplementacion;
import Logica.Actividad;
import Main.WindowManager;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Kojiro
 */
public class ActividadAmbiental extends javax.swing.JPanel {

    private int idUsuario;

    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    
    @Override
    public void setVisible(boolean visible) {
        super.setVisible(visible);
        if (visible) {
            this.MostrarTabla();
        }
    }
    
    Principal p;
    public ActividadAmbiental(Principal p) {
        this.p=p;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        Table_Actividades = new javax.swing.JTable();
        Button_CrearActividad = new javax.swing.JToggleButton();

        setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setText("Actividad Ambiental");

        Table_Actividades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(Table_Actividades);

        jScrollPane4.setViewportView(jScrollPane5);

        Button_CrearActividad.setText("Generar Actividad");
        Button_CrearActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CrearActividadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(194, Short.MAX_VALUE)
                .addComponent(Button_CrearActividad)
                .addGap(177, 177, 177))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(71, 71, 71))
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(68, 68, 68)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(Button_CrearActividad)
                .addContainerGap(79, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Button_CrearActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CrearActividadActionPerformed
        GenerarActividad ga=new GenerarActividad();
        p.MostrarPanel(ga);
    }//GEN-LAST:event_Button_CrearActividadActionPerformed
    
    public void MostrarTabla() {
        DAOactividadImplementacion actividadImpl = new DAOactividadImplementacion();
        ArrayList<Actividad> actividades = actividadImpl.Seleccionar();

        DefaultTableModel modelo = new DefaultTableModel();

        modelo.addColumn("Titulo");
        modelo.addColumn("Descripción");
        modelo.addColumn("Distrito");
        modelo.addColumn("fecha");
        Table_Actividades.setModel(modelo);

        String[] datos = new String[4];

        for (Actividad actividad : actividades) {
            if (actividad.isAceptado()) {
                datos[0] = actividad.getTitulo();
                datos[1] = actividad.getDescripcion();
                datos[2] = actividad.getDistrito();
                datos[3] = actividad.getFecha();
                modelo.addRow(datos);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Button_CrearActividad;
    private javax.swing.JTable Table_Actividades;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables
}
