package Interfaz;

import DAO.DAOarticuloImplementacion;
import DAO.DAOarticulofavoritoImplementacion;
import Logica.Articulo;
import Main.WindowManager;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class JFrame_MostrarArticulo extends javax.swing.JFrame {

    private int idArticulo;
    private int idUsuario;

    public void setidArticulo(int idArticulo) {
        this.idArticulo = idArticulo;
    }

    public void getIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

    @Override
    public void setVisible(boolean visible) {
        super.setVisible(visible);
        if (visible) {
            this.idArticulo = WindowManager.getIdArticulo();
            this.idUsuario = WindowManager.getIdUsuario();
            try {
                MostrarArticulo();
            } catch (Exception ex) {
                Logger.getLogger(JFrame_MostrarArticulo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    public JFrame_MostrarArticulo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        Text_Titulo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Text_Descripcion = new javax.swing.JTextArea();
        Text_Usuario = new javax.swing.JLabel();
        Text_Fecha = new javax.swing.JLabel();
        Button_Regresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Button_favorito = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 153), 3, true));
        jPanel1.setPreferredSize(new java.awt.Dimension(360, 480));

        Text_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Text_Titulo.setText("Titulo");

        Text_Descripcion.setColumns(20);
        Text_Descripcion.setRows(5);
        jScrollPane2.setViewportView(Text_Descripcion);

        Text_Usuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Text_Usuario.setText("Autor");

        Text_Fecha.setText("Fecha");

        Button_Regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        Button_Regresar.setBorder(null);
        Button_Regresar.setBorderPainted(false);
        Button_Regresar.setContentAreaFilled(false);
        Button_Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_RegresarActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo-principal.png"))); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Button_favorito.setText("Favorito");
        Button_favorito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_favoritoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Text_Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                            .addComponent(Text_Fecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Text_Usuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Button_Regresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Button_favorito)
                .addGap(110, 110, 110))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_Regresar)
                    .addComponent(jLabel2))
                .addGap(15, 15, 15)
                .addComponent(Text_Titulo)
                .addGap(10, 10, 10)
                .addComponent(Text_Fecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Text_Usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(Button_favorito)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_RegresarActionPerformed
        this.dispose();
        WindowManager.showWindow("frameArticulo");
    }//GEN-LAST:event_Button_RegresarActionPerformed

    private void Button_favoritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_favoritoActionPerformed
        DAOarticulofavoritoImplementacion articuloFav = new DAOarticulofavoritoImplementacion();
        try {
            boolean favorito = !articuloFav.Buscar(idArticulo, idUsuario);
            articuloFav.Modificar(favorito, idArticulo, idUsuario);
            if(favorito){
                JOptionPane.showMessageDialog(null, "Agregado a favoritos");
            }else{
                JOptionPane.showMessageDialog(null, "Eliminado de favoritos");
            }
            MostrarArticulo();
        } catch (Exception ex) {
            Logger.getLogger(JFrame_MostrarArticulo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Button_favoritoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_MostrarArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_MostrarArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_MostrarArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_MostrarArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_MostrarArticulo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Regresar;
    private javax.swing.JButton Button_favorito;
    private javax.swing.JTextArea Text_Descripcion;
    private javax.swing.JLabel Text_Fecha;
    private javax.swing.JLabel Text_Titulo;
    private javax.swing.JLabel Text_Usuario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
    public void MostrarArticulo() throws Exception {
        try {
            DAOarticuloImplementacion articuloImpl = new DAOarticuloImplementacion();

            // Obtener el artículo desde la base de datos
            Articulo articulo = articuloImpl.SeleccionarD(this.idArticulo);

            // Mostrar los datos en los componentes de la ventana
            if (articulo != null) {
                Text_Titulo.setText("Título: " + articulo.getTitulo());
                Text_Descripcion.setText(articulo.getDescripcion());
                Text_Fecha.setText("Fecha: " + articulo.getFecha());
                Text_Usuario.setText("Autor: " + articulo.getNombreUsuario());
            } else {
                System.out.println("Artículo no encontrado.");
            }
        } catch (Exception e) {
            System.err.println("Error al mostrar artículo: " + e.getMessage());
        }

        DAOarticulofavoritoImplementacion articuloFav = new DAOarticulofavoritoImplementacion();
        if (articuloFav.Buscar(idArticulo, idUsuario)) {
            Button_favorito.setBackground(Color.yellow);
            Button_favorito.setText("Eliminar de favoritos");
        } else {
            Button_favorito.setBackground(Color.white);
            Button_favorito.setText("Eliminar de favoritos");
            Button_favorito.setText("Agregar a favoritos");
        }
    }

}
