/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

import CadenaDeResponsabilidad.ValidadorLink;
import CadenaDeResponsabilidad.ValidadorVacio;
import DAO.DAOtiendaImplementacion;
import Interfaces.Validador;
import Logica.Tienda;
import Main.WindowManager;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kojiro
 */
public class TiendasAdministrativo extends javax.swing.JPanel {

    private int idAdministrador;

    public void setIdUsuario(int idUsuario) {
        this.idAdministrador = idUsuario;
    }

    @Override
    public void setVisible(boolean visible) {
        super.setVisible(visible);
        if (visible) {
            this.idAdministrador = WindowManager.getIdUsuario(); // Obtener el ID del usuario actual
            this.MostrarTabla();
        }
    }
    
    Principal p;
    public TiendasAdministrativo(Principal p) {
        this.p=p;
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_Tiendas = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        Text_Link = new javax.swing.JTextField();
        Button_Agregar = new javax.swing.JButton();
        Button_Eliminar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Text_Nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Text_IdTienda = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setText("Tiendas Online");

        Table_Tiendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(Table_Tiendas);

        jScrollPane1.setViewportView(jScrollPane2);

        jLabel3.setText("Link");

        Text_Link.setText(" ");

        Button_Agregar.setText("Agregar");
        Button_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_AgregarActionPerformed(evt);
            }
        });

        Button_Eliminar.setText("Eliminar");
        Button_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_EliminarActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre");

        Text_Nombre.setText(" ");
        Text_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_NombreActionPerformed(evt);
            }
        });

        jLabel2.setText("ID de tienda");

        Text_IdTienda.setText(" ");
        Text_IdTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_IdTiendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Text_Link, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                    .addComponent(Text_Nombre)
                                    .addComponent(Text_IdTienda))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Button_Agregar)
                                    .addComponent(Button_Eliminar))
                                .addGap(35, 35, 35))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(Button_Agregar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Text_IdTienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button_Eliminar)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Text_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Text_Link, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Button_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_AgregarActionPerformed
        this.AñadirTienda();
    }//GEN-LAST:event_Button_AgregarActionPerformed

    private void Button_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_EliminarActionPerformed
        this.EliminarTienda();
    }//GEN-LAST:event_Button_EliminarActionPerformed

    private void Text_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_NombreActionPerformed

    private void Text_IdTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_IdTiendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_IdTiendaActionPerformed
    public void MostrarTabla() {
        DAOtiendaImplementacion tiendaImpl = new DAOtiendaImplementacion();
        ArrayList<Tienda> tiendas = tiendaImpl.Seleccionar();

        DefaultTableModel modelo = new DefaultTableModel();

        modelo.addColumn("Id Tienda");
        modelo.addColumn("Nombre");
        modelo.addColumn("Link");
        Table_Tiendas.setModel(modelo);

        String[] datos = new String[3];

        for (Tienda tienda : tiendas) {
            datos[0] = String.valueOf(tienda.getIdTienda());
            datos[1] = tienda.getNombre();
            datos[2] = tienda.getLink();
            modelo.addRow(datos);
        }
    }

    public void AñadirTienda() {
        Validador validadorNombre = new ValidadorVacio();
        Validador validadorLinkVacio = new ValidadorVacio();

        Validador validadorLink = new ValidadorLink();
        validadorLinkVacio.setSiguiente(validadorLink);

        try {
            validadorNombre.validar(Text_Nombre);
            validadorLinkVacio.validar(Text_Link);

            DAOtiendaImplementacion tiendaImpl = new DAOtiendaImplementacion();
            Tienda tienda = new Tienda();
            tienda.setIdAdministrador(idAdministrador);
            tienda.setNombre(Text_Nombre.getText());
            tienda.setLink(Text_Link.getText());

            if (tiendaImpl.Registrar(tienda) == true) {
                JOptionPane.showMessageDialog(null, "Tienda agregada con exito");
                this.MostrarTabla();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void EliminarTienda() {
        Validador validadorIdTienda = new ValidadorVacio();

        try {
            validadorIdTienda.validar(Text_IdTienda);

            DAOtiendaImplementacion tiendaImpl = new DAOtiendaImplementacion();

            if (tiendaImpl.Eliminar(Integer.parseInt(Text_IdTienda.getText())) == true) {
                JOptionPane.showMessageDialog(null, "Tienda eliminada");
                this.MostrarTabla();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Agregar;
    private javax.swing.JButton Button_Eliminar;
    private javax.swing.JTable Table_Tiendas;
    private javax.swing.JTextField Text_IdTienda;
    private javax.swing.JTextField Text_Link;
    private javax.swing.JTextField Text_Nombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
