/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

import CadenaDeResponsabilidad.ValidadorCorreo;
import CadenaDeResponsabilidad.ValidadorTelefono;
import CadenaDeResponsabilidad.ValidadorVacio;
import DAO.DAOclienteImplementacion;
import Interfaces.Validador;
import Main.WindowManager;
import javax.swing.JOptionPane;

/**
 *
 * @author Kojiro
 */
public class Usuario extends javax.swing.JPanel {

    private int idUsuario;

    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

    @Override
    public void setVisible(boolean visible) {
        super.setVisible(visible);
        if (visible) {
            this.idUsuario = WindowManager.getIdUsuario(); // Obtener el ID del usuario actual
        }
    }
    public Usuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Text_Nombres = new javax.swing.JTextField();
        Text_Usuario = new javax.swing.JTextField();
        Text_Distrito = new javax.swing.JTextField();
        Text_Telefono = new javax.swing.JTextField();
        Text_Correo = new javax.swing.JTextField();
        Text_Contraseña = new javax.swing.JTextField();
        Button_Actualizar = new javax.swing.JButton();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Usuario.png"))); // NOI18N

        jLabel14.setText("Nombre");

        jLabel15.setText("Usuario");

        jLabel16.setText("Telefono");

        jLabel17.setText("Distrito");

        jLabel18.setText("Correo");

        jLabel19.setText("Contraseña");

        Text_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_UsuarioActionPerformed(evt);
            }
        });

        Text_Distrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_DistritoActionPerformed(evt);
            }
        });

        Text_Telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_TelefonoActionPerformed(evt);
            }
        });

        Text_Correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_CorreoActionPerformed(evt);
            }
        });

        Text_Contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_ContraseñaActionPerformed(evt);
            }
        });

        Button_Actualizar.setText("Actualizar");
        Button_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(Text_Nombres, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                    .addComponent(Text_Usuario)
                    .addComponent(Text_Distrito, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Text_Telefono)
                    .addComponent(Text_Correo)
                    .addComponent(Text_Contraseña, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(54, 54, 54))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Button_Actualizar)
                .addGap(208, 208, 208))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text_Nombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(Text_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text_Distrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(38, 38, 38)
                .addComponent(Button_Actualizar)
                .addContainerGap(55, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Text_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_UsuarioActionPerformed

    private void Text_DistritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_DistritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_DistritoActionPerformed

    private void Text_TelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_TelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_TelefonoActionPerformed

    private void Text_CorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_CorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_CorreoActionPerformed

    private void Text_ContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_ContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_ContraseñaActionPerformed

    private void Button_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ActualizarActionPerformed
                Validador validadorNombre = new ValidadorVacio();
        Validador validadorUser = new ValidadorVacio();
        Validador validadorCorreoVacio = new ValidadorVacio();
        Validador validadorTelefonoVacio = new ValidadorVacio();
        Validador validadorDistritoVacio = new ValidadorVacio();
        Validador validadorContraseñaVacio = new ValidadorVacio();

        Validador validadorCorreo = new ValidadorCorreo();
        validadorCorreoVacio.setSiguiente(validadorCorreo);

        Validador validadorTelefono = new ValidadorTelefono();
        validadorTelefonoVacio.setSiguiente(validadorTelefono);

        try {
            validadorNombre.validar(Text_Nombres);
            validadorUser.validar(Text_Usuario);
            validadorCorreoVacio.validar(Text_Correo);
            validadorTelefonoVacio.validar(Text_Telefono);
            validadorDistritoVacio.validar(Text_Distrito);
            validadorContraseñaVacio.validar(Text_Contraseña);

            Logica.Cliente cliente = new Logica.Cliente();
            cliente.setNombre(Text_Nombres.getText().trim());
            cliente.setUsuario(Text_Usuario.getText().trim());
            cliente.setCorreo(Text_Correo.getText().trim());
            cliente.setTelefono(Text_Telefono.getText().trim());
            cliente.setDistrito(Text_Distrito.getText().trim());
            cliente.setPassword(Text_Contraseña.getText().trim());

            DAOclienteImplementacion clientImpl = new DAOclienteImplementacion();
            if (clientImpl.Modificar(cliente) == true) {
                JOptionPane.showMessageDialog(null, "Modificacion correcta");
                Text_Nombres.setText("");
                Text_Usuario.setText("");
                Text_Correo.setText("");
                Text_Telefono.setText("");
                Text_Distrito.setText("");
                Text_Contraseña.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Error al modificar usuario");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_Button_ActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Actualizar;
    private javax.swing.JTextField Text_Contraseña;
    private javax.swing.JTextField Text_Correo;
    private javax.swing.JTextField Text_Distrito;
    private javax.swing.JTextField Text_Nombres;
    private javax.swing.JTextField Text_Telefono;
    private javax.swing.JTextField Text_Usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    // End of variables declaration//GEN-END:variables
}
